#--------------------------------------------------------------------------------------------------
# Lunar Ctrls
#--------------------------------------------------------------------------------------------------




templateLC = {
	"minimalDefinition": {
		# Base (required)
		"Hips": 									{"id": 1,		"node": "pelvis_ctrl"},
		"LeftUpLeg": 							{"id": 2,		"node": "thigh_l_ctrl"},
		"LeftLeg":								{"id": 3,		"node": "calf_l_ctrl"},
		"LeftFoot": 							{"id": 4,		"node": "foot_l_ctrl"},
		"RightUpLeg": 						{"id": 5,		"node": "thigh_r_ctrl"},
		"RightLeg":								{"id": 6,		"node": "calf_r_ctrl"},
		"RightFoot":							{"id": 7,		"node": "foot_r_ctrl"},
		"Spine":									{"id": 8,		"node": "spine_01_ctrl"},
		"LeftArm":								{"id": 9,		"node": "upperarm_l_ctrl"},
		"LeftForeArm":						{"id": 10, 	"node": "lowerarm_l_ctrl"},
		"LeftHand":								{"id": 11, 	"node": "hand_l_ctrl"},
		"RightArm":								{"id": 12, 	"node": "upperarm_r_ctrl"},
		"RightForeArm":						{"id": 13, 	"node": "lowerarm_r_ctrl"},
		"RightHand":							{"id": 14, 	"node": "hand_r_ctrl"},
		"Head":										{"id": 15, 	"node": "head_ctrl"},
	},
	"definition": {
		# "Reference": 							{"id": 0,	"node": "root_ctrl"},
    "Root": 									{"id": 500,	"node": "root_ctrl"},
		# Base (required)
		"Hips":										{"id": 1, 	"node": "pelvis_ctrl"},
		"LeftUpLeg": 							{"id": 2, 	"node": "thigh_l_ctrl"},
		"LeftLeg": 								{"id": 3, 	"node": "calf_l_ctrl"},
		"LeftFoot": 							{"id": 4, 	"node": "foot_l_ctrl"},
		"RightUpLeg":							{"id": 5, 	"node": "thigh_r_ctrl"},
		"RightLeg": 							{"id": 6, 	"node": "calf_r_ctrl"},
		"RightFoot": 							{"id": 7, 	"node": "foot_r_ctrl"},
		"Spine": 									{"id": 8, 	"node": "spine_01_ctrl"},
		"LeftArm": 								{"id": 9, 	"node": "upperarm_l_ctrl"},
		"LeftForeArm": 						{"id": 10, 	"node": "lowerarm_l_ctrl"},
		"LeftHand": 							{"id": 11, 	"node": "hand_l_ctrl"},
		"RightArm": 							{"id": 12, 	"node": "upperarm_r_ctrl"},
		"RightForeArm": 					{"id": 13, 	"node": "lowerarm_r_ctrl"},
		"RightHand": 							{"id": 14, 	"node": "hand_r_ctrl"},
		"Head": 									{"id": 15, 	"node": "head_ctrl"},
		# Auxiliary
		"LeftToeBase": 						{"id": 16, 	"node": "ball_l_ctrl"},
		"RightToeBase": 					{"id": 17, 	"node": "ball_r_ctrl"},
		"LeftShoulder": 					{"id": 18, 	"node": "clavicle_l_ctrl"},
		"RightShoulder": 					{"id": 19, 	"node": "clavicle_r_ctrl"},
		"Neck": 									{"id": 20, 	"node": "neck_01_ctrl"},
		# Spine
		"Spine1": 								{"id": 23, 	"node": "spine_02_ctrl"},
		"Spine2": 								{"id": 24, 	"node": "spine_03_ctrl"},
		"Spine3": 								{"id": 25, 	"node": "spine_04_ctrl"},
		"Spine4": 								{"id": 26, 	"node": "spine_05_ctrl"},
		# Neck
		"Neck1": 									{"id": 32, 	"node": "neck_02_ctrl"},
		# Roll - Leaf
		# We don't bake the twist ctrls because they're calculated in the solver
		"LeafLeftArmRoll1": 			{"id": 176, "node": "upperarm_twist_01_l_ctrl"},
		"LeafLeftArmRoll2": 			{"id": 184, "node": "upperarm_twist_02_l_ctrl"},
		"LeafLeftForeArmRoll1": 	{"id": 177, "node": "lowerarm_twist_02_l_ctrl"},
		"LeafLeftForeArmRoll2": 	{"id": 185, "node": "lowerarm_twist_01_l_ctrl"},
		"LeafRightArmRoll1":			{"id": 178, "node": "upperarm_twist_01_r_ctrl"},
		"LeafRightArmRoll2":			{"id": 186, "node": "upperarm_twist_02_r_ctrl"},
		"LeafRightForeArmRoll1": 	{"id": 179, "node": "lowerarm_twist_02_r_ctrl"},
		"LeafRightForeArmRoll2": 	{"id": 187, "node": "lowerarm_twist_01_r_ctrl"},
		"LeafLeftUpLegRoll1": 		{"id": 172, "node": "thigh_twist_01_l_ctrl"},
		"LeafLeftUpLegRoll2": 		{"id": 180, "node": "thigh_twist_02_l_ctrl"},
		"LeafLeftLegRoll1": 			{"id": 173, "node": "calf_twist_02_l_ctrl"},
		"LeafLeftLegRoll2": 			{"id": 181, "node": "calf_twist_01_l_ctrl"},
		"LeafRightUpLegRoll1": 		{"id": 174, "node": "thigh_twist_01_r_ctrl"},
		"LeafRightUpLegRoll2": 		{"id": 182, "node": "thigh_twist_02_r_ctrl"},
		"LeafRightLegRoll1": 			{"id": 175, "node": "calf_twist_02_r_ctrl"},
		"LeafRightLegRoll2": 			{"id": 183, "node": "calf_twist_01_r_ctrl"},
		# Left Hand
		"LeftHandThumb1": 				{"id": 50, 	"node": "thumb_01_l_ctrl"},
		"LeftHandThumb2": 				{"id": 51, 	"node": "thumb_02_l_ctrl"},
		"LeftHandThumb3": 				{"id": 52, 	"node": "thumb_03_l_ctrl"},
		"LeftHandIndex1": 				{"id": 54, 	"node": "index_01_l_ctrl"},
		"LeftHandIndex2": 				{"id": 55, 	"node": "index_02_l_ctrl"},
		"LeftHandIndex3": 				{"id": 56, 	"node": "index_03_l_ctrl"},
		"LeftHandMiddle1": 				{"id": 58, 	"node": "middle_01_l_ctrl"},
		"LeftHandMiddle2": 				{"id": 59, 	"node": "middle_02_l_ctrl"},
		"LeftHandMiddle3": 				{"id": 60, 	"node": "middle_03_l_ctrl"},
		"LeftHandRing1": 					{"id": 62, 	"node": "ring_01_l_ctrl"},
		"LeftHandRing2": 					{"id": 63, 	"node": "ring_02_l_ctrl"},
		"LeftHandRing3": 					{"id": 64, 	"node": "ring_03_l_ctrl"},
		"LeftHandPinky1": 				{"id": 66, 	"node": "pinky_01_l_ctrl"},
		"LeftHandPinky2": 				{"id": 67, 	"node": "pinky_02_l_ctrl"},
		"LeftHandPinky3": 				{"id": 68, 	"node": "pinky_03_l_ctrl"},
		# Right Hand
		"RightHandThumb1": 				{"id": 74, 	"node": "thumb_01_r_ctrl"},
		"RightHandThumb2": 				{"id": 75, 	"node": "thumb_02_r_ctrl"},
		"RightHandThumb3": 				{"id": 76, 	"node": "thumb_03_r_ctrl"},
		"RightHandIndex1": 				{"id": 78, 	"node": "index_01_r_ctrl"},
		"RightHandIndex2": 				{"id": 79, 	"node": "index_02_r_ctrl"},
		"RightHandIndex3": 				{"id": 80, 	"node": "index_03_r_ctrl"},
		"RightHandMiddle1": 			{"id": 82, 	"node": "middle_01_r_ctrl"},
		"RightHandMiddle2": 			{"id": 83, 	"node": "middle_02_r_ctrl"},
		"RightHandMiddle3": 			{"id": 84, 	"node": "middle_03_r_ctrl"},
		"RightHandRing1": 				{"id": 86, 	"node": "ring_01_r_ctrl"},
		"RightHandRing2": 				{"id": 87, 	"node": "ring_02_r_ctrl"},
		"RightHandRing3": 				{"id": 88, 	"node": "ring_03_r_ctrl"},
		"RightHandPinky1": 				{"id": 90, 	"node": "pinky_01_r_ctrl"},
		"RightHandPinky2": 				{"id": 91, 	"node": "pinky_02_r_ctrl"},
		"RightHandPinky3": 				{"id": 92, 	"node": "pinky_03_r_ctrl"},
		# Inner Finger
		"LeftInHandIndex": 				{"id": 147, "node": "index_metacarpal_l_ctrl"},
		"LeftInHandMiddle": 			{"id": 148, "node": "middle_metacarpal_l_ctrl"},
		"LeftInHandRing":					{"id": 149, "node": "ring_metacarpal_l_ctrl"},
		"LeftInHandPinky": 				{"id": 150, "node": "pinky_metacarpal_l_ctrl"},
		"RightInHandIndex": 			{"id": 153, "node": "index_metacarpal_r_ctrl"},
		"RightInHandMiddle": 			{"id": 154, "node": "middle_metacarpal_r_ctrl"},
		"RightInHandRing": 				{"id": 155, "node": "ring_metacarpal_r_ctrl"},
		"RightInHandPinky": 			{"id": 156, "node": "pinky_metacarpal_r_ctrl"},
		# Left Foot
		"LeftFootIndex1": 				{"id": 102, "node": "indextoe_01_l_ctrl"},
		"LeftFootIndex2": 				{"id": 103, "node": "indextoe_02_l_ctrl"},
		"LeftFootMiddle1": 				{"id": 106, "node": "middletoe_01_l_ctrl"},
		"LeftFootMiddle2": 				{"id": 107, "node": "middletoe_02_l_ctrl"},
		"LeftFootRing1": 					{"id": 110, "node": "ringtoe_01_l_ctrl"},
		"LeftFootRing2": 					{"id": 111, "node": "ringtoe_02_l_ctrl"},
		"LeftFootPinky1": 				{"id": 114, "node": "littletoe_01_l_ctrl"},
		"LeftFootPinky2": 				{"id": 115, "node": "littletoe_02_l_ctrl"},
		# "LeftFootExtraFinger1": 	{"id": 118, "node": "ball_l_ctrl"},
		# "LeftFootExtraFinger1": 	{"id": 118, "node": "bigtoe_01_l_ctrl"},
		# "LeftFootExtraFinger2": 	{"id": 119, "node": "bigtoe_02_l_ctrl"},
		# Left Foot
		"RightFootIndex1": 				{"id": 126, "node": "indextoe_01_r_ctrl"},
		"RightFootIndex2": 				{"id": 127, "node": "indextoe_02_r_ctrl"},
		"RightFootMiddle1": 			{"id": 130, "node": "middletoe_01_r_ctrl"},
		"RightFootMiddle2": 			{"id": 131, "node": "middletoe_02_r_ctrl"},
		"RightFootRing1": 				{"id": 134, "node": "ringtoe_01_r_ctrl"},
		"RightFootRing2": 				{"id": 135, "node": "ringtoe_02_r_ctrl"},
		"RightFootPinky1": 				{"id": 138, "node": "littletoe_01_r_ctrl"},
		"RightFootPinky2": 				{"id": 139, "node": "littletoe_02_r_ctrl"},
		# "RightFootExtraFinger1": 	{"id": 142, "node": "ball_r_ctrl"},
		# "RightFootExtraFinger1": 	{"id": 142, "node": "bigtoe_01_r_ctrl"},
		# "RightFootExtraFinger2": 	{"id": 143, "node": "bigtoe_02_r_ctrl"},
	},
	"tPose": {
		'arm_ik_l_ctrl': {'rotateX': -5.724998426634331e-14,
											'rotateY': 6.361109362927035e-15,
											'rotateZ': 6.36110936292703e-15,
											'space': 1,
											'translateX': -7.105427357601002e-15,
											'translateY': 2.842170943040401e-14,
											'translateZ': 8.881784197001252e-15,
											'visibility': True},
		'arm_ik_r_ctrl': {'rotateX': -1.2722218725854073e-14,
											'rotateY': 1.5952469574215454e-14,
											'rotateZ': -1.5455507905236783e-14,
											'space': 1,
											'translateX': -2.1316282072803006e-14,
											'translateY': -1.4210854715202004e-14,
											'translateZ': 0.0,
											'visibility': True},
		'arm_pv_l_ctrl': {'space': 1,
											'translateX': 7.105427357601002e-15,
											'translateY': 7.105427357601002e-15,
											'translateZ': -1.4210854715202004e-14,
											'visibility': True},
		'arm_pv_r_ctrl': {'space': 1,
											'translateX': 7.105427357601002e-15,
											'translateY': -7.105427357601002e-15,
											'translateZ': 0.0,
											'visibility': True},
		'ball_l_ctrl': {'rotateX': 0.0, 'rotateY': 0.0, 'rotateZ': 0.0},
		'ball_r_ctrl': {'rotateX': 0.0, 'rotateY': 0.0, 'rotateZ': 0.0},
		'calf_l_ctrl': {'rotateZ': 0.0},
		'calf_r_ctrl': {'rotateZ': 0.0},
		'clavicle_l_ctrl': {'rotateX': 0.0, 'rotateY': 0.0, 'rotateZ': 0.0},
		'clavicle_r_ctrl': {'rotateX': 0.0, 'rotateY': 0.0, 'rotateZ': 0.0},
		'fkik_ctrl': {'leftArmFkIk': 0.0,
									'leftArmSoftness': 0.0,
									'leftArmTwist': 0.0,
									'leftLegFkIk': 0.0,
									'leftLegSoftness': 0.0,
									'leftLegTwist': 0.0,
									'rightArmFkIk': 0.0,
									'rightArmSoftness': 0.0,
									'rightArmTwist': 0.0,
									'rightLegFkIk': 0.0,
									'rightLegSoftness': 0.0,
									'rightLegTwist': 0.0},
		'foot_l_ctrl': {'rotateX': 0.0, 'rotateY': 0.0, 'rotateZ': 0.0},
		'foot_r_ctrl': {'rotateX': 0.0, 'rotateY': 0.0, 'rotateZ': 0.0},
		'hand_l_ctrl': {'rotateX': 0.0, 'rotateY': 0.0, 'rotateZ': 0.0, 'space': 4},
		'hand_r_ctrl': {'rotateX': 0.0, 'rotateY': 0.0, 'rotateZ': 0.0, 'space': 4},
		'head_ctrl': {'rotateX': 0.0, 'rotateY': 0.0, 'rotateZ': 0.0},
		'leg_ik_l_ctrl': {'rotateX': 5.4069429584879776e-14,
											'rotateY': -1.5902773407317578e-14,
											'rotateZ': -3.180554681463524e-15,
											'space': 2,
											'translateX': -1.7763568394002505e-15,
											'translateY': -1.1102230246251565e-16,
											'translateZ': -3.552713678800501e-15,
											'visibility': True},
		'leg_ik_r_ctrl': {'rotateX': 9.223608576244199e-14,
											'rotateY': 6.361109362927069e-15,
											'rotateZ': -4.452776554048923e-14,
											'space': 2,
											'translateX': 1.7763568394002505e-15,
											'translateY': 0.0,
											'translateZ': -1.7763568394002505e-15,
											'visibility': True},
		'leg_pv_l_ctrl': {'space': 2,
											'translateX': 0.0,
											'translateY': 0.0,
											'translateZ': 0.0,
											'visibility': True},
		'leg_pv_r_ctrl': {'space': 2,
											'translateX': 0.0,
											'translateY': 0.0,
											'translateZ': 0.0,
											'visibility': True},
		'lowerarm_l_ctrl': {'rotateZ': 36.38719642655931},
		'lowerarm_r_ctrl': {'rotateZ': 36.387},
		'lowerarm_twist_01_l_ctrl': {'rotateX': 0.0, 'rotateY': 0.0, 'rotateZ': 0.0},
		'lowerarm_twist_01_r_ctrl': {'rotateX': 0.0, 'rotateY': 0.0, 'rotateZ': 0.0},
		'main_ctrl': {'rotateX': 0.0,
									'rotateY': 0.0,
									'rotateZ': 0.0,
									'translateX': 0.0,
									'translateY': 0.0,
									'translateZ': 0.0},
		'middle_01_l_ctrl': {'rotateX': 0.0,
													'rotateY': 0.0,
													'rotateZ': 0.0,
													'translateX': 0.0,
													'translateY': 0.0,
													'translateZ': 0.0},
		'middle_01_r_ctrl': {'rotateX': 0.0,
													'rotateY': 0.0,
													'rotateZ': 0.0,
													'translateX': 0.0,
													'translateY': 0.0,
													'translateZ': 0.0},
		'middle_02_l_ctrl': {'rotateX': 0.0,
													'rotateY': 0.0,
													'rotateZ': 0.0,
													'translateX': 0.0,
													'translateY': 0.0,
													'translateZ': 0.0},
		'middle_02_r_ctrl': {'rotateX': 0.0,
													'rotateY': 0.0,
													'rotateZ': 0.0,
													'translateX': 0.0,
													'translateY': 0.0,
													'translateZ': 0.0},
		'middle_03_l_ctrl': {'rotateX': 0.0,
													'rotateY': 0.0,
													'rotateZ': 0.0,
													'translateX': 0.0,
													'translateY': 0.0,
													'translateZ': 0.0},
		'middle_03_r_ctrl': {'rotateX': 0.0,
													'rotateY': 0.0,
													'rotateZ': 0.0,
													'translateX': 0.0,
													'translateY': 0.0,
													'translateZ': 0.0},
		'middle_metacarpal_l_ctrl': {'rotateX': 0.0,
																	'rotateY': 0.0,
																	'rotateZ': 0.0,
																	'translateX': 0.0,
																	'translateY': 0.0,
																	'translateZ': 0.0},
		'middle_metacarpal_r_ctrl': {'rotateX': 0.0,
																	'rotateY': 0.0,
																	'rotateZ': 0.0,
																	'translateX': 0.0,
																	'translateY': 0.0,
																	'translateZ': 0.0},
		'neck_01_ctrl': {'rotateX': 0.0,
											'rotateY': 0.0,
											'rotateZ': 0.0,
											'space': 4,
											'translateX': -5.421010862427522e-20,
											'translateY': 0.0,
											'translateZ': 0.0},
		'neck_02_ctrl': {'rotateX': 0.0,
											'rotateY': 0.0,
											'rotateZ': 0.0,
											'translateX': 0.0,
											'translateY': 0.0,
											'translateZ': 0.0},
		'pelvis_ctrl': {'rotateX': 0.0,
										'rotateY': 0.0,
										'rotateZ': 0.0,
										'space': 2,
										'translateX': 0.0,
										'translateY': 0.0,
										'translateZ': -3.1554436208840472e-30},
		'pelvis_detach_ctrl': {'rotateX': 0.0,
														'rotateY': 0.0,
														'rotateZ': 0.0,
														'translateX': 0.0,
														'translateY': 0.0,
														'translateZ': 0.0},
		'pelvis_end_ctrl': {'rotateX': 0.0,
												'rotateY': 0.0,
												'rotateZ': 0.0,
												'translateX': 0.0,
												'translateY': 0.0,
												'translateZ': 0.0},
		'pelvis_rot_ctrl': {'rotateX': 0.0, 'rotateY': 0.0, 'rotateZ': 0.0},
		'root_ctrl': {'rotateX': 0.0,
									'rotateY': 0.0,
									'rotateZ': 0.0,
									'space': 1,
									'translateX': 6.310887241768095e-30,
									'translateY': -8.881784197001252e-16,
									'translateZ': 1.9721522630525295e-31},
		'spine_00_ctrl': {'rotateX': 0.0, 'rotateY': 0.0, 'rotateZ': 0.0},
		'spine_01_ctrl': {'rotateX': 0.0, 'rotateY': 0.0, 'rotateZ': 0.0},
		'spine_02_ctrl': {'rotateX': 0.0, 'rotateY': 0.0, 'rotateZ': 0.0},
		'spine_03_ctrl': {'rotateX': 0.0, 'rotateY': 0.0, 'rotateZ': 0.0},
		'spine_04_ctrl': {'rotateX': 0.0, 'rotateY': 0.0, 'rotateZ': 0.0},
		'spine_05_ctrl': {'rotateX': 0.0, 'rotateY': 0.0, 'rotateZ': 0.0},
		'spine_06_ctrl': {'rotateX': 0.0, 'rotateY': 0.0, 'rotateZ': 0.0},
		'spine_07_ctrl': {'rotateX': 0.0, 'rotateY': 0.0, 'rotateZ': 0.0},
		'spine_08_ctrl': {'rotateX': 0.0, 'rotateY': 0.0, 'rotateZ': 0.0},
		'thigh_l_ctrl': {'rotateX': 0.0, 'rotateY': 0.0, 'rotateZ': 0.0},
		'thigh_r_ctrl': {'rotateX': 0.0, 'rotateY': 0.0, 'rotateZ': 0.0},
		'thumb_01_l_ctrl': {'rotateX': 0.0,
												'rotateY': 0.0,
												'rotateZ': 0.0,
												'translateX': 0.0,
												'translateY': 0.0,
												'translateZ': 0.0},
		'thumb_01_r_ctrl': {'rotateX': 0.0,
												'rotateY': 0.0,
												'rotateZ': 0.0,
												'translateX': 0.0,
												'translateY': 0.0,
												'translateZ': 0.0},
		'thumb_02_l_ctrl': {'rotateX': 0.0,
												'rotateY': 0.0,
												'rotateZ': 0.0,
												'translateX': 0.0,
												'translateY': 0.0,
												'translateZ': 0.0},
		'thumb_02_r_ctrl': {'rotateX': 0.0,
												'rotateY': 0.0,
												'rotateZ': 0.0,
												'translateX': 0.0,
												'translateY': 0.0,
												'translateZ': 0.0},
		'thumb_03_l_ctrl': {'rotateX': 0.0,
												'rotateY': 0.0,
												'rotateZ': 0.0,
												'translateX': 0.0,
												'translateY': 0.0,
												'translateZ': 0.0},
		'thumb_03_r_ctrl': {'rotateX': 0.0,
												'rotateY': 0.0,
												'rotateZ': 0.0,
												'translateX': 0.0,
												'translateY': 0.0,
												'translateZ': 0.0},
		'upperarm_l_ctrl': {'rotateX': 65.0,
												'rotateY': 0.0,
												'rotateZ': 59.99999999999999},
		'upperarm_r_ctrl': {'rotateX': 65.0,
												'rotateY': 0.0,
												'rotateZ': 59.99999999999999},
		'weapon_l_ctrl': {'rotateX': 0.0,
											'rotateY': 0.0,
											'rotateZ': 0.0,
											'translateX': 0.0,
											'translateY': 0.0,
											'translateZ': 0.0},
		'weapon_r_ctrl': {'rotateX': 0.0,
											'rotateY': 0.0,
											'rotateZ': 0.0,
											'translateX': 0.0,
											'translateY': 0.0,
											'translateZ': 0.0}
	},
	"aPose": {
		'arm_ik_l_ctrl': {'rotateX': 0.0,
											'rotateY': 0.0,
											'rotateZ': 0.0,
											'space': 1,
											'translateX': 0.0,
											'translateY': 0.0,
											'translateZ': 0.0,
											'visibility': True},
		'arm_ik_r_ctrl': {'rotateX': 0.0,
											'rotateY': 0.0,
											'rotateZ': 0.0,
											'space': 1,
											'translateX': 0.0,
											'translateY': 0.0,
											'translateZ': -2.220446049250313e-16,
											'visibility': True},
		'arm_pv_l_ctrl': {'space': 1,
											'translateX': 0.0,
											'translateY': 4.336808689942018e-19,
											'translateZ': 6.661338147750939e-16,
											'visibility': True},
		'arm_pv_r_ctrl': {'space': 1,
											'translateX': 1.1102230246251565e-16,
											'translateY': 0.0,
											'translateZ': 2.220446049250313e-16,
											'visibility': True},
		'ball_l_ctrl': {'rotateX': 0.0, 'rotateY': 0.0, 'rotateZ': 0.0},
		'ball_r_ctrl': {'rotateX': 0.0, 'rotateY': 0.0, 'rotateZ': 0.0},
		'calf_l_ctrl': {'rotateZ': 0.0},
		'calf_r_ctrl': {'rotateZ': 0.0},
		'clavicle_l_ctrl': {'rotateX': 0.0, 'rotateY': 0.0, 'rotateZ': 0.0},
		'clavicle_r_ctrl': {'rotateX': 0.0, 'rotateY': 0.0, 'rotateZ': 0.0},
		'fkik_ctrl': {'leftArmFkIk': 0.0,
									'leftArmSoftness': 0.0,
									'leftArmTwist': 0.0,
									'leftLegFkIk': 100.0,
									'leftLegSoftness': 0.0,
									'leftLegTwist': 0.0,
									'rightArmFkIk': 0.0,
									'rightArmSoftness': 0.0,
									'rightArmTwist': 0.0,
									'rightLegFkIk': 100.0,
									'rightLegSoftness': 0.0,
									'rightLegTwist': 0.0},
		'foot_l_ctrl': {'rotateX': 0.0, 'rotateY': 0.0, 'rotateZ': 0.0},
		'foot_r_ctrl': {'rotateX': 0.0, 'rotateY': 0.0, 'rotateZ': 0.0},
		'hand_l_ctrl': {'rotateX': 0.0, 'rotateY': 0.0, 'rotateZ': 0.0, 'space': 4},
		'hand_r_ctrl': {'rotateX': 0.0, 'rotateY': 0.0, 'rotateZ': 0.0, 'space': 4},
		'head_ctrl': {'rotateX': 0.0, 'rotateY': 0.0, 'rotateZ': 0.0},
		'leg_ik_l_ctrl': {'rotateX': 0.0,
											'rotateY': 0.0,
											'rotateZ': 0.0,
											'space': 2,
											'translateX': -2.7755575615628914e-17,
											'translateY': 0.0,
											'translateZ': 0.0},
		'leg_ik_r_ctrl': {'rotateX': 0.0,
											'rotateY': 0.0,
											'rotateZ': 0.0,
											'space': 2,
											'translateX': 2.7755575615628914e-17,
											'translateY': 0.0,
											'translateZ': 0.0},
		'leg_pv_l_ctrl': {'space': 2,
											'translateX': 0.0,
											'translateY': 0.0,
											'translateZ': 5.551115123125783e-17},
		'leg_pv_r_ctrl': {'space': 2,
											'translateX': 0.0,
											'translateY': 2.220446049250313e-16,
											'translateZ': -5.551115123125783e-17},
		'lowerarm_l_ctrl': {'rotateZ': 0.0},
		'lowerarm_r_ctrl': {'rotateZ': 0.0},
		'lowerarm_twist_01_l_ctrl': {'rotateX': 0.0, 'rotateY': 0.0, 'rotateZ': 0.0},
		'lowerarm_twist_01_r_ctrl': {'rotateX': 0.0, 'rotateY': 0.0, 'rotateZ': 0.0},
		'main_ctrl': {'rotateX': 0.0,
									'rotateY': 0.0,
									'rotateZ': 0.0,
									'translateX': 0.0,
									'translateY': 0.0,
									'translateZ': 0.0},
		'middle_01_l_ctrl': {'rotateX': 0.0,
													'rotateY': 0.0,
													'rotateZ': 0.0,
													'translateX': 0.0,
													'translateY': 0.0,
													'translateZ': 0.0},
		'middle_01_r_ctrl': {'rotateX': 0.0,
													'rotateY': 0.0,
													'rotateZ': 0.0,
													'translateX': 0.0,
													'translateY': 0.0,
													'translateZ': 0.0},
		'middle_02_l_ctrl': {'rotateX': 0.0,
													'rotateY': 0.0,
													'rotateZ': 0.0,
													'translateX': 0.0,
													'translateY': 0.0,
													'translateZ': 0.0},
		'middle_02_r_ctrl': {'rotateX': 0.0,
													'rotateY': 0.0,
													'rotateZ': 0.0,
													'translateX': 0.0,
													'translateY': 0.0,
													'translateZ': 0.0},
		'middle_03_l_ctrl': {'rotateX': 0.0,
													'rotateY': 0.0,
													'rotateZ': 0.0,
													'translateX': 0.0,
													'translateY': 0.0,
													'translateZ': 0.0},
		'middle_03_r_ctrl': {'rotateX': 0.0,
													'rotateY': 0.0,
													'rotateZ': 0.0,
													'translateX': 0.0,
													'translateY': 0.0,
													'translateZ': 0.0},
		'middle_metacarpal_l_ctrl': {'rotateX': 0.0,
																	'rotateY': 0.0,
																	'rotateZ': 0.0,
																	'translateX': 0.0,
																	'translateY': 0.0,
																	'translateZ': 0.0},
		'middle_metacarpal_r_ctrl': {'rotateX': 0.0,
																	'rotateY': 0.0,
																	'rotateZ': 0.0,
																	'translateX': 0.0,
																	'translateY': 0.0,
																	'translateZ': 0.0},
		'neck_01_ctrl': {'rotateX': 0.0,
											'rotateY': 0.0,
											'rotateZ': 0.0,
											'space': 4,
											'translateX': -5.421010862427522e-20,
											'translateY': 0.0,
											'translateZ': 0.0},
		'neck_02_ctrl': {'rotateX': 0.0,
											'rotateY': 0.0,
											'rotateZ': 0.0,
											'translateX': 0.0,
											'translateY': 0.0,
											'translateZ': 0.0},
		'pelvis_ctrl': {'rotateX': 0.0,
										'rotateY': 0.0,
										'rotateZ': 0.0,
										'space': 2,
										'translateX': 4.930380657631324e-32,
										'translateY': 0.0,
										'translateZ': 1.5407439555097887e-33},
		'pelvis_detach_ctrl': {'rotateX': 0.0,
														'rotateY': 0.0,
														'rotateZ': 0.0,
														'translateX': 0.0,
														'translateY': 0.0,
														'translateZ': 0.0},
		'pelvis_end_ctrl': {'rotateX': 0.0,
												'rotateY': 0.0,
												'rotateZ': 0.0,
												'translateX': 0.0,
												'translateY': 0.0,
												'translateZ': 0.0},
		'pelvis_rot_ctrl': {'rotateX': 0.0, 'rotateY': 0.0, 'rotateZ': 0.0},
		'root_ctrl': {'rotateX': 0.0,
									'rotateY': 0.0,
									'rotateZ': 0.0,
									'space': 1,
									'translateX': 0.0,
									'translateY': 0.0,
									'translateZ': 0.0},
		'spine_00_ctrl': {'rotateX': 0.0, 'rotateY': 0.0, 'rotateZ': 0.0},
		'spine_01_ctrl': {'rotateX': 0.0, 'rotateY': 0.0, 'rotateZ': 0.0},
		'spine_02_ctrl': {'rotateX': 0.0, 'rotateY': 0.0, 'rotateZ': 0.0},
		'spine_03_ctrl': {'rotateX': 0.0, 'rotateY': 0.0, 'rotateZ': 0.0},
		'spine_04_ctrl': {'rotateX': 0.0, 'rotateY': 0.0, 'rotateZ': 0.0},
		'spine_05_ctrl': {'rotateX': 0.0, 'rotateY': 0.0, 'rotateZ': 0.0},
		'spine_06_ctrl': {'rotateX': 0.0, 'rotateY': 0.0, 'rotateZ': 0.0},
		'spine_07_ctrl': {'rotateX': 0.0, 'rotateY': 0.0, 'rotateZ': 0.0},
		'spine_08_ctrl': {'rotateX': 0.0, 'rotateY': 0.0, 'rotateZ': 0.0},
		'thigh_l_ctrl': {'rotateX': 0.0, 'rotateY': 0.0, 'rotateZ': 0.0},
		'thigh_r_ctrl': {'rotateX': 0.0, 'rotateY': 0.0, 'rotateZ': 0.0},
		'thumb_01_l_ctrl': {'rotateX': 0.0,
												'rotateY': 0.0,
												'rotateZ': 0.0,
												'translateX': 0.0,
												'translateY': 0.0,
												'translateZ': 0.0},
		'thumb_01_r_ctrl': {'rotateX': 0.0,
												'rotateY': 0.0,
												'rotateZ': 0.0,
												'translateX': 0.0,
												'translateY': 0.0,
												'translateZ': 0.0},
		'thumb_02_l_ctrl': {'rotateX': 0.0,
												'rotateY': 0.0,
												'rotateZ': 0.0,
												'translateX': 0.0,
												'translateY': 0.0,
												'translateZ': 0.0},
		'thumb_02_r_ctrl': {'rotateX': 0.0,
												'rotateY': 0.0,
												'rotateZ': 0.0,
												'translateX': 0.0,
												'translateY': 0.0,
												'translateZ': 0.0},
		'thumb_03_l_ctrl': {'rotateX': 0.0,
												'rotateY': 0.0,
												'rotateZ': 0.0,
												'translateX': 0.0,
												'translateY': 0.0,
												'translateZ': 0.0},
		'thumb_03_r_ctrl': {'rotateX': 0.0,
												'rotateY': 0.0,
												'rotateZ': 0.0,
												'translateX': 0.0,
												'translateY': 0.0,
												'translateZ': 0.0},
		'upperarm_l_ctrl': {'rotateX': 0.0, 'rotateY': 0.0, 'rotateZ': 0.0},
		'upperarm_r_ctrl': {'rotateX': 0.0, 'rotateY': 0.0, 'rotateZ': 0.0},
		'weapon_l_ctrl': {'rotateX': 0.0,
											'rotateY': 0.0,
											'rotateZ': 0.0,
											'translateX': 0.0,
											'translateY': 0.0,
											'translateZ': 0.0},
		'weapon_r_ctrl': {'rotateX': 0.0,
											'rotateY': 0.0,
											'rotateZ': 0.0,
											'translateX': 0.0,
											'translateY': 0.0,
											'translateZ': 0.0}
	}
}
